# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
  branches:
    include:
    - master
    - releases/*

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build job
    steps:
    - script: | 
        echo Hello, world !! 
        echo Replace me with your build steps      
- stage: DeployFromMaster
  displayName: Production stage
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:  
  - job: prodDeploy
    displayName: prod deploy
    steps:
    - script: | 
        echo deploying to prod environment 
        echo prod env deployed 
- stage: DeployFromPR
  displayName: Production stage  
  dependsOn: Build
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/pull'))
  jobs:  
  - job: transientDeploy
    displayName: transient deploy
    steps:
    - script: | 
        echo deploying to transient env environment 
        echo transient env deployed 
